#!/bin/bash

set -e

export HITHER_VERSION=`cat version`

echo Building docker image for hither-$HITHER_VERSION

sed -s s/_VERSION_/$HITHER_VERSION/ < Dockerfile.template > Dockerfile

./activator dist
docker build -t wiredthing/hither .
docker tag wiredthing/hither wiredthing/hither:$HITHER_VERSION

rm Dockerfile
