FROM dockerfile/java
MAINTAINER Doug Clinton <doug@wiredthing.com>

VOLUME ["/tmp/work"]

WORKDIR /tmp/work

ADD target/universal/hither-_VERSION_.zip /tmp/work/hither.zip
RUN unzip hither && mv /tmp/work/hither-_VERSION_ /opt/hither

VOLUME ["/opt/hither/localRegistry"]

EXPOSE 9000

WORKDIR /root

CMD ["/bin/bash", "/opt/hither/bin/hither", "-mem", "384"]